global:
  bpversion: NA
  git:
    provider: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    target: HEAD

  quay:
    provider: quay.io
    account: PLAINTEXT
