apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  TEST: {{ .Values.global.bpversion }}
  IMAGE_PROVIDER: {{ .Values.global.quay.provider }}
  IMAGE_ACCOUNT: {{ .Values.global.quay.account }}
  GIT_EMAIL: {{ .Values.global.git.email }}
  GIT_USERNAME: {{ .Values.global.git.username }}
  GIT_DEV_REPO_URL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/manuela-dev.git
  GIT_OPS_REPO_TEST_URL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
  GIT_OPS_REPO_PROD_URL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
  IOT_CONSUMER_IMAGE: iot-consumer
  IOT_CONSUMER_YAML_PATH: images.(name==messaging).newTag
  IOT_CONSUMER_TEST_KUSTOMIZATION_PATH: config/instances/manuela-tst/kustomization.yaml
  IOT_CONSUMER_PROD_KUSTOMIZATION_PATH: manufacturing-edge-ai-ml/datacenter/manuela/messaging/kustomization.yaml
  IOT_CONSUMER_PROD_IMAGESTREAM_PATH: manufacturing-edge-ai-ml/datacenter/manuela/messaging/messaging-is.yaml
  IOT_FRONTEND_IMAGE: iot-frontend
  IOT_FRONTEND_YAML_PATH: images.(name==line-dashboard).newTag
  IOT_FRONTEND_TEST_KUSTOMIZATION_PATH: config/instances/manuela-tst/kustomization.yaml
  IOT_FRONTEND_PROD_KUSTOMIZATION_PATH: manufacturing-edge-ai-ml/datacenter/manuela/line-dashboard/kustomization.yaml
  IOT_FRONTEND_PROD_IMAGESTREAM_PATH: manufacturing-edge-ai-ml/datacenter/manuela/line-dashboard/line-dashboard-is.yaml
  IOT_SWSENSOR_IMAGE: iot-software-sensor
  IOT_SWSENSOR_YAML_PATH: images.(name==machine-sensor).newTag
  IOT_SWSENSOR_TEST_KUSTOMIZATION_PATH: config/instances/manuela-tst/kustomization.yaml
  IOT_SWSENSOR_PROD_KUSTOMIZATION_PATH: manufacturing-edge-ai-ml/datacenter/manuela/machine-sensor/kustomization.yaml
  IOT_SWSENSOR_PROD_IMAGESTREAM_PATH: manufacturing-edge-ai-ml/datacenter/manuela/machine-sensor/machine-sensor-is.yaml
  IOT_ANOMALY_IMAGE: iot-anomaly-detection
  IOT_ANOMALY_YAML_PATH: images.(name==anomaly-detection).newTag
  IOT_ANOMALY_TEST_KUSTOMIZATION_PATH: config/instances/manuela-tst/kustomization.yaml
  IOT_ANOMALY_PROD_KUSTOMIZATION_PATH: manufacturing-edge-ai-ml/datacenter/manuela/anomaly-detection/kustomization.yaml
  IOT_ANOMALY_PROD_IMAGESTREAM_PATH: manufacturing-edge-ai-ml/datacenter/manuela/anomaly-detection/anomaly-detection-is.yaml
