apiVersion: v1
kind: Namespace
metadata:
  name: staging
  annotations:
    argocd.argoproj.io/sync-wave: 1
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: staging
    gitops-mgmt: argocd
    manuela: factory
  name: staging
  annotations:
    argocd.argoproj.io/sync-wave: 2
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: staging
  namespace: staging
  annotations:
    argocd.argoproj.io/sync-wave: 2
spec:
  clusterName: staging
  clusterNamespace: staging
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.0.0
